# Project info
site_name: IBM Sales Enablement - L3 - Creation  Guidance
site_description: Guidance for creating L3 content and learning plans for Sales Enablement
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/SalesEnablement-L3-Guidance
docs_dir: docs


nav:
  - Home: README.md
  - Part 1 - Setting up your Mac
    - 'Introduction': 'mac-setup/01 Introduction.md'
    - 'Install git': 'mac-setup/02 Install git.md'
    - 'Install MkDocs and plugins': 'mac-setup/03 Install MKDCOS and plugins.md'
    - 'The Atom editor': 'mac-setup/04 The Atom editor.md'
  - Part 2 - Setting up your Git repository
    - 'Introduction': 'git-setup/01 Introduction.md'
    - 'Create IBM GitHub repository': 'git-setup/02 Create IBM GitHub respository'
    - 'Configure GitHub Pages': 'git-setup/03 Configure GitHub Pages.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - search
    - mkdocs-video
    - macros

extra:
  generator: false

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys

extra:
  learningplan:
    name: "IBM Cloud Satellite Sales Level 3"
    url: "https://yourlearning/"
  tz_environment:
    name: "IBM Cloud Satellite - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
    uuid_label: "Demo-UUID"
  account: "2435442 - ITZ - Satellite"
  aws:
    location: aws-us-east-2
    host_ip: ip-10-0-1-114
    cluster_name: aws_os_cluster
    cluster_id: c7o5jt8w0o6g5fkl3rp0
    ingress: aws-os-cluster-222b3514854c2221251113b2b051506c-0000.upi.containers.appdomain.cloud
  ibm:
    cluster_name: ibmcloud-wdc-os
    cluster_id: c7o68suw0jvhnc82ukg0
    ingress: ibmcloud-wdc-os-222b3514854c2221251113b2b051506c-0000.us-east.containers.appdomain.cloud
